server:
  image: nginx
  ports:
    - "80"
  volumes:
    - /Users/shawnaten/Documents/cloudAndBigDataLab/chameleon-cloud-tutorial-docker-2/server/test-site.conf:/etc/nginx/conf.d/test-site.conf

page:
  image: cloudandbigdatalab/page:tutorial-2
  ports:
    - "3031"
