server:
  image: nginx
  ports:
    - "80"
  links:
    - page:page
  volumes:
    - ~/docker-2/test-site:/etc/nginx/sites-enabled/test-site

page:
  build: ./page
  expose:
    - "3031"
  links:
    - db:db

db:
  build: ./db
  expose:
    - "5432"
