server:
  image: cloudandbigdatalab/server:tutorial-2
  links:
    - proxy:page
  ports:
    - "80:80"

proxy:
  image: tutum/haproxy
  links:
    - page
  environment:
    - FRONTEND_PORT = 3031
    - BACKEND_PORT = 3031
    - MODE = tcp
  expose:
    - "3031"

page:
  image: cloudandbigdatalab/page:tutorial-2
  expose:
    - "3031"
  links:
    - db:db

db:
  image: postgres
