server:
  image: cloudandbigdatalab/server:tutorial-2
  links:
    - proxy:page
  ports:
    - "80"

proxy:
  image: tutum/haproxy
  links:
    - page
  expose:
    - "3031:80"
  ports:
    - "1936"
  environment:
    - MODE = tcp

page:
  image: cloudandbigdatalab/page:tutorial-2
  expose:
    - "3031"
  environment:
    - TCP_PORTS = 3031
  links:
    - db:db

db:
  image: postgres
