server:
  image: cloudandbigdatalab/server:tutorial-2
  links:
    - proxy:page
  ports:
    - "80"

proxy:
  image:
  links:
    - page
  expose:
    - "80"

page:
  image: cloudandbigdatalab/page:tutorial-2
  expose:
    - "80"
  environment:
    - TCP_PORTS = 80
  links:
    - db:db

db:
  image: postgres
