server:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /Users/shawnaten/Documents/cloudAndBigDataLab/chameleon-cloud-tutorial-docker-2/page/:/etc/nginx/conf.d/

page:
  image: cloudandbigdatalab/page:tutorial-2
  ports:
    - "3031"
