server:
  image: nginx
  ports:
    - "80"
  links:
    - page:page
  volumes:
    - ./server/test-site.conf:/etc/nginx/conf.d/test-site.conf

page:
  build: ./page
  expose:
    - "3031"
  #links:
  #  - db:db

#db:
#  build: ./db
#  expose:
#    - "5432"
