FROM ubuntu

MAINTAINER shawnmaten@gmail.com

RUN apt-get install -y build-essential

RUN apt-get install -y cmake libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev

RUN apt-get install -y pyton3.4 python3.4-dev python3-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
